# GoReleaser configuration for FlowGauge
# Documentation: https://goreleaser.com

version: 2

project_name: flowgauge

before:
  hooks:
    - go mod tidy

builds:
  - id: flowgauge
    main: ./cmd/flowgauge
    binary: flowgauge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/lan-dot-party/flowgauge/pkg/version.Version={{.Version}}
      - -X github.com/lan-dot-party/flowgauge/pkg/version.Commit={{.Commit}}
      - -X github.com/lan-dot-party/flowgauge/pkg/version.BuildDate={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - configs/flowgauge.example.yaml

nfpms:
  - id: packages
    package_name: flowgauge
    vendor: lan-dot-party
    homepage: https://github.com/lan-dot-party/flowgauge
    maintainer: lan-dot-party
    description: |
      FlowGauge - Bandwidth monitoring with Multi-WAN support.
      A modular bandwidth testing tool with DSCP tagging,
      scheduled tests, REST API and Prometheus metrics.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      # Config directory
      - src: configs/flowgauge.example.yaml
        dst: /etc/flowgauge/config.yaml.example
        type: config
      # Systemd service
      - src: scripts/systemd/flowgauge.service
        dst: /lib/systemd/system/flowgauge.service
        type: config
    scripts:
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh
    overrides:
      deb:
        dependencies:
          - ca-certificates
      rpm:
        dependencies:
          - ca-certificates

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: lan-dot-party
    name: flowgauge
  draft: false
  prerelease: auto
  name_template: "FlowGauge v{{.Version}}"

dockers:
  - id: flowgauge-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/lan-dot-party/flowgauge:{{ .Version }}-amd64"
      - "ghcr.io/lan-dot-party/flowgauge:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=FlowGauge"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/lan-dot-party/flowgauge"

  - id: flowgauge-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/lan-dot-party/flowgauge:{{ .Version }}-arm64"
      - "ghcr.io/lan-dot-party/flowgauge:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=FlowGauge"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/lan-dot-party/flowgauge"

docker_manifests:
  - name_template: "ghcr.io/lan-dot-party/flowgauge:{{ .Version }}"
    image_templates:
      - "ghcr.io/lan-dot-party/flowgauge:{{ .Version }}-amd64"
      - "ghcr.io/lan-dot-party/flowgauge:{{ .Version }}-arm64"
  - name_template: "ghcr.io/lan-dot-party/flowgauge:latest"
    image_templates:
      - "ghcr.io/lan-dot-party/flowgauge:latest-amd64"
      - "ghcr.io/lan-dot-party/flowgauge:latest-arm64"


